### ISSUE TITLE
dmesg -T time is not inaccurate

### ISSUE THREAD

**Issue by pc10201** [euank/go-kmsg-parser#5]
dmesg -T time is not inaccurate

go-kmsg-parser time  is not inaccurate too

Can you fix it?

**Comment by euank** [comment]
This is a limitation of the kernel kmsg interface, unfortunately.

If you're curious, the problem here is that [kmsg is specified to have the monotonic time](https://www.kernel.org/doc/Documentation/ABI/testing/dev-kmsg) only, and, as the kernel docs say, [monotonic time](https://www.kernel.org/doc/html/latest/core-api/timekeeping.html#c.ktime_get) pauses during suspend.

The most common reason dmesg times are inaccurate is because that clock "pauses" while the computer is suspended (like a laptop lid closed), but there's other ways for it to become wrong.

There's not enough information to reconstruct the actual time. I think both dmesg and this package try to get the real time by adding the "monotonic time seconds" to the [boot time](https://github.com/euank/go-kmsg-parser/blob/9b879671614de5794be7017d566c49d2c6c87957/kmsgparser/kmsgparser.go#L191-L192), which as above gives a wrong value in several cases.

If you need accurate timestamps for your dmesg logs, I'd recommend using `journalctl -t kernel` to view kmsg logs, as well as the time journald received them. That time should be accurate in many more cases.
