### ISSUE TITLE
When will the parser.Parse() ends?

### ISSUE THREAD

**Issue by sfc-gh-pchu** [euank/go-kmsg-parser#8]
Hi,

I am using the example code to parse message, but the below for loop never ends. And I find the channel will be closed only when it encounters EOF or an error(https://github.com/euank/go-kmsg-parser/blob/6575cc091819c8335dec98d8517b11203f5ba93c/kmsgparser/kmsgparser.go#L136). But I doubt the way you read the /dev/kmsg will never meets EOF, and the read will always be blocked if there is no new message. Is that the correct way to implement that? How to close the goroutine or channel if there are no new messages just like dmesg linux command.
```go
	kmsg := parser.Parse()

	for msg := range kmsg {
		fmt.Printf("(%d) - %s: %s", msg.SequenceNumber, msg.Timestamp.Format(time.RFC3339Nano), msg.Message)
	}

``` 
Thanks a lot!

**Comment by euank** [comment]
I think the `io.EOF` can happen because there's a `Close()` method which will close the reader.

https://github.com/euank/go-kmsg-parser/blob/6575cc091819c8335dec98d8517b11203f5ba93c/kmsgparser/kmsgparser.go#L102-L104

However, that's not the same as how `dmesg` works, since that requires the caller to close it (perhaps after a period of inactivity).

`dmesg` instead uses nonblocking reads and waits for an EAGAIN from the device. in C, that's easy enough, but the go runtime, which does epoll-based io under the hood, makes it a little trickier to do that right.

I put up a PR over here which implements the nonblocking reading and EAGAIN detection, and in that PR also updated the example program to have a follow/no-follow flag: https://github.com/euank/go-kmsg-parser/pull/9

Would you like to check if that PR does what you're looking for?

**Comment by sfc-gh-pchu** [comment]
Hi, 
Thanks for replying! Yeah there is a Close() function to cause EOF. The delay parse.Close() will be executed when the function ends. But then comes to the dead loop that for loop always blocks and the defer function won't get a chance to run. Or do you have other better way to run the Close() function to trigger EOF.
https://github.com/euank/go-kmsg-parser/blob/6575cc091819c8335dec98d8517b11203f5ba93c/cmd/godmesg/main.go#L36

The non-blocking way to read the file is what I expect! The PR looks good to me.

**Comment by euank** [comment]
I've release [v3.0.0](https://github.com/euank/go-kmsg-parser/releases/tag/v3.0.0), which should fix this issue.

I also included other breaking changes, since I think I got the interface wrong the first time, so it might require a little additional refactoring to use.

Something like the following should work:

```go
parser, err := kmsgparser.NewParser(kmsgparser.WithNoFollow())
if err != nil { ... }
msgs := make(chan kmsgparser.Message, 10)
go func() {
	// Note: _always_ closes `msgs`
	if err := parser.Parse(msgs); err != nil {
		log.Warnf("error parsing /dev/kmsg: %v", err)
	}
}()

// since 'Parse' always closes msgs, it's safe to loop over it like so:
for msg := range msgs {
	// handle message
}
```

Let me know if you run into any other issues or such!

I'll close this as hopefully resolved with that release
